/**
 * The NYC Compass - Curated Places Database
 * Categories: 'eat', 'visit', 'nightlife'
 * Boroughs: 'Manhattan', 'Brooklyn', 'Queens', 'The Bronx', 'Staten Island'
 */

const NYC_PLACES = [
  // ==========================================
  // BEST PLACES TO EAT
  // ==========================================
  {
    id: "katzs-delicatessen",
    name: "Katz's Delicatessen",
    category: "eat",
    subCategory: "Iconic Jewish Deli & Pastrami",
    borough: "Manhattan",
    neighborhood: "Lower East Side",
    address: "205 E Houston St, New York, NY 10002",
    subway: "F train to 2nd Ave or F/M/J/Z to Delancey St-Essex St",
    price: "$$",
    rating: 4.8,
    reviewsCount: "38,000+",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The undisputed king of pastrami on rye, serving legendary cured meats since 1888.",
    fullDesc: "Established in 1888, Katz's is New York's oldest and most iconic Jewish delicatessen. Famous for carving warm, thick-cut pastrami and corned beef by hand behind counter cutters who hand you a sample slice while you wait. Immortalized in pop culture (notably 'When Harry Met Sally'), it remains an unmatched sensory experience of classic New York grit and glory.",
    mustTry: ["Pastrami on Rye with brown mustard", "Matzo Ball Soup", "Half-Sour Pickles", "Dr. Brown's Cel-Ray Soda"],
    proTip: "Hold onto your paper ticket tightly! If you lose it upon exiting, there is a legendary $50 penalty. Tip the cutter a dollar or two when you order for an extra generous sandwich.",
    tags: ["Historic", "Jewish Deli", "Iconic", "Late Night", "Carnivore"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Katz%27s_Delicatessen"
  },
  {
    id: "joes-pizza",
    name: "Joe's Pizza (The Greenwich Village Original)",
    category: "eat",
    subCategory: "Classic NYC Slice",
    borough: "Manhattan",
    neighborhood: "Greenwich Village",
    address: "7 Carmine St, New York, NY 10014",
    subway: "A, C, E, B, D, F, M to W 4th St-Wash Sq",
    price: "$",
    rating: 4.9,
    reviewsCount: "22,000+",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The benchmark of a classic New York thin-crust cheese slice since 1975 by Naples native Joe Pozzuoli.",
    fullDesc: "Founded in 1975 by Italian immigrant Pino 'Joe' Pozzuoli, Joe's Pizza on Carmine Street is widely hailed as the quintessential New York street slice: blistered crisp crust, perfectly balanced tangy tomato sauce, and molten whole-milk mozzarella that folds neatly without flopping.",
    mustTry: ["Plain Cheese Slice (hot out of the oven)", "Fresh Mozzarella Slice", "Pepperoni Slice"],
    proTip: "Eat it standing up at the counter or outside on Carmine St. Fold the slice in half lengthwise like a true New Yorker to prevent cheese slide and lock in the heat.",
    tags: ["Pizza", "Grab & Go", "Late Night", "Celebrity Favorite"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Joe%27s_Pizza"
  },
  {
    id: "lucali-brooklyn",
    name: "Lucali",
    category: "eat",
    subCategory: "Wood-Fired Brick Oven Pizza & Calzone",
    borough: "Brooklyn",
    neighborhood: "Carroll Gardens",
    address: "575 Henry St, Brooklyn, NY 11231",
    subway: "F, G to Carroll St",
    price: "$$$",
    rating: 4.9,
    reviewsCount: "5,400+",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Mark Iacono's candlelit brick-oven temple revered by Beyoncé, Jay-Z, and pizza devotees worldwide.",
    fullDesc: "Located in a former candy store in Brooklyn, Lucali offers a candlelit, BYOB dining room where Mark Iacono rolls out pizza dough using empty wine bottles. With its blistered thin crust, three-cheese blend (mozzarella, buffalo mozzarella, and Grana Padano), and rich simmered sauce, it is considered by many critics to be the greatest pizza in North America.",
    mustTry: ["Large Pie with Pepperoni, Basil, and Shallots", "Legendary Ricotta Calzone"],
    proTip: "No online reservations! Line up by 3:30 PM to 4:00 PM on the sidewalk; at 5:00 PM the staff comes out with the reservation book to assign tables for the evening. It's strictly cash-only and BYOB (bring your own wine).",
    tags: ["Pizza", "Romantic", "Bucket List", "BYOB", "Cash Only"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Lucali"
  },
  {
    id: "russ-and-daughters",
    name: "Russ & Daughters",
    category: "eat",
    subCategory: "Appetizing & Smoked Fish",
    borough: "Manhattan",
    neighborhood: "Lower East Side",
    address: "179 E Houston St, New York, NY 10002",
    subway: "F to 2nd Ave",
    price: "$$",
    rating: 4.8,
    reviewsCount: "8,900+",
    image: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Fourth-generation Jewish appetizing institution known for silk-cut Nova lox, bagels, and caviar.",
    fullDesc: "Operating continuously since 1914, Joel Russ started selling herring from a pushcart before opening this legendary shop, proudly naming it 'Russ & Daughters'—the first business in the United States to include '& Daughters' in its official title. Famous for sliced-to-order Gaspe Nova salmon, handmade cream cheeses, babka, and bialys.",
    mustTry: ["The Classic Board (Gaspe Nova smoked salmon, cream cheese, tomato, red onion, capers on an all-seed bagel)", "Chocolate Babka", "Super Heebster"],
    proTip: "Take a paper number at the original shop for takeout, or walk down Orchard St to their sit-down Russ & Daughters Cafe for vintage Jewish diner charm and cocktails.",
    tags: ["Bagels", "Smoked Fish", "Historic", "Breakfast & Brunch"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Russ_%26_Daughters"
  },
  {
    id: "nom-wah-tea-parlor",
    name: "Nom Wah Tea Parlor",
    category: "eat",
    subCategory: "Vintage Dim Sum",
    borough: "Manhattan",
    neighborhood: "Chinatown",
    address: "13 Doyers St, New York, NY 10013",
    subway: "J, Z, 6, N, Q, R, W to Canal St",
    price: "$$",
    rating: 4.6,
    reviewsCount: "12,500+",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=80",
    shortDesc: "NYC's oldest dim sum parlor, tucked away on Chinatown's historic curving Doyers 'Bloody Angle'.",
    fullDesc: "First opened in 1920 as a bakery and tea parlor, Nom Wah is Chinatown's longest continually operating restaurant. Perched on Doyers Street—the historic curving alley once dubbed the 'Bloody Angle' during early 20th-century Tong Wars—Nom Wah now offers fresh made-to-order dim sum, retro red vinyl booths, and nostalgic vintage vibes.",
    mustTry: ["The Original 'OG' Egg Roll", "Shrimp & Snow Pea Leaf Dumplings", "Pan-fried Pork Buns", "Turnip Cakes"],
    proTip: "Unlike traditional banquet halls with pushcarts, dishes here are made fresh to order. Put your name on the waitlist and grab a craft cocktail at the subterranean speakeasy 'Apotheke' right next door.",
    tags: ["Dim Sum", "Historic", "Chinatown", "Dumplings"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Nom_Wah_Tea_Parlor"
  },
  {
    id: "le-bernardin",
    name: "Le Bernardin",
    category: "eat",
    subCategory: "3-Star Michelin Haute Cuisine",
    borough: "Manhattan",
    neighborhood: "Midtown West",
    address: "155 W 51st St, New York, NY 10019",
    subway: "1 to 50th St or N, Q, R, W to 49th St",
    price: "$$$$",
    rating: 4.9,
    reviewsCount: "6,200+",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Chef Eric Ripert's globally revered temple of seafood, holding three Michelin stars and four NYT stars.",
    fullDesc: "Originally founded in Paris by Maguy and Gilbert Le Coze and brought to New York in 1986, Le Bernardin is widely celebrated as one of the finest restaurants on planet Earth. Under Chef Eric Ripert, the kitchen prepares seafood under three distinct philosophies: 'Almost Raw', 'Barely Touched', and 'Lightly Cooked'.",
    mustTry: ["Yellowfin Tuna Carpaccio over Foie Gras", "Poached Halibut with Daikon Radish", "Four-Course Prix Fixe or Chef's Tasting Menu"],
    proTip: "Reservations drop on the 1st of every month at 9:00 AM ET for the following month and sell out in 90 seconds. For a more accessible experience, walk into the Lounge at Le Bernardin without a reservation for an à la carte menu.",
    tags: ["Fine Dining", "Michelin 3-Star", "Seafood", "Special Occasion"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Le_Bernardin"
  },
  {
    id: "los-tacos-no-1",
    name: "Los Tacos No. 1",
    category: "eat",
    subCategory: "Authentic Tijuana-Style Tacos",
    borough: "Manhattan",
    neighborhood: "Chelsea / Times Square",
    address: "Chelsea Market, 75 9th Ave, New York, NY 10011",
    subway: "A, C, E, L to 14th St-8th Ave",
    price: "$",
    rating: 4.8,
    reviewsCount: "19,000+",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The pinnacle of NYC street tacos created by three close friends from Tijuana, Mexico and Brawley, California.",
    fullDesc: "With warm, fresh-pressed corn and flour tortillas made right before your eyes and meats grilled over charcoal, Los Tacos No. 1 has taken New York by storm. The trompo of marinated Adobada pork with roasted pineapple is sheer culinary perfection.",
    mustTry: ["Adobada Pork Taco 'Con Todo' (guacamole, onions, cilantro, salsa)", "Carne Asada Especial (fried quesadilla shell topped with beef)", "Agua de Horchata"],
    proTip: "The line moves lightning-fast—order first at the cashier register, grab your paper ticket, and take it to the taqueros at the grill. Always say 'con todo' for the full avocado salsa.",
    tags: ["Mexican", "Street Food", "Budget Friendly", "Quick Bite"]
  },
  {
    id: "robertos-arthur-avenue",
    name: "Roberto's (The Real Little Italy)",
    category: "eat",
    subCategory: "Southern Italian / Salerno",
    borough: "The Bronx",
    neighborhood: "Belmont / Arthur Avenue",
    address: "603 Crescent Ave, Bronx, NY 10458",
    subway: "Metro-North to Fordham or B, D to Fordham Rd",
    price: "$$$",
    rating: 4.7,
    reviewsCount: "3,800+",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Chef Roberto Paciullo's soul-stirring Salerno dishes in NYC's true, authentic Little Italy.",
    fullDesc: "While Manhattan's Mulberry Street has become largely touristy, Arthur Avenue in the Bronx is where locals go for authentic Italian culinary heritage. Roberto's serves legendary homemade pasta wrapped in foil or parchment paper and baked, allowing garlic, tomatoes, seafood, and herbs to infuse completely.",
    mustTry: ["Radiatori in Cartoccio (pasta with mushrooms, cherry tomatoes, and truffle oil baked in foil)", "Polenta Cinghiále (wild boar sauce)", "Veal Osso Buco"],
    proTip: "Combine dinner with an afternoon stroll down Arthur Avenue: visit Mike's Deli inside the Arthur Avenue Retail Market, Madonia Brothers Bakery for fresh cannoli, and Casa Della Mozzarella for warm fresh cheese.",
    tags: ["Bronx", "Little Italy", "Pasta", "Authentic"]
  },
  {
    id: "jackson-heights-himalayan",
    name: "Jackson Heights Himalayan & South Asian Hub",
    category: "eat",
    subCategory: "Tibetan Momos & Indian Thali",
    borough: "Queens",
    neighborhood: "Jackson Heights",
    address: "37-47 74th St, Jackson Heights, NY 11372",
    subway: "7, E, F, M, R to Jackson Hts-Roosevelt Ave",
    price: "$",
    rating: 4.7,
    reviewsCount: "7,200+",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The culinary heart of the most culturally diverse neighborhood on Earth.",
    fullDesc: "Jackson Heights in Queens boasts speakers of over 160 languages. Along 74th Street and Roosevelt Avenue, you'll discover fragrant Indian thalis, steaming Tibetan momo dumplings (like Lhasa Fast Food tucked behind a cellphone repair shop), Colombian bakeries, and Mexican birria carts.",
    mustTry: ["Tibetan Beef Momos with fiery chili oil", "Chana Masala & Garlic Naan", "Colombian Buñuelos & Pan de Bono", "Chaat from street carts"],
    proTip: "Take an empty stomach and an open mind. Start under the elevated 7 train on Roosevelt Ave, sample street momos, then walk over to 74th street for aromatic sweets and chai.",
    tags: ["Queens", "Global Flavors", "Dumplings", "Street Food", "Spicy"]
  },
  {
    id: "levain-bakery",
    name: "Levain Bakery",
    category: "eat",
    subCategory: "Giant 6-Ounce Cookies",
    borough: "Manhattan",
    neighborhood: "Upper West Side",
    address: "167 W 74th St, New York, NY 10023",
    subway: "1, 2, 3 to 72nd St",
    price: "$",
    rating: 4.9,
    reviewsCount: "16,800+",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Famed for mammoth, gooey, six-ounce chocolate chip walnut cookies that redefined baking in NYC.",
    fullDesc: "Founded in 1995 by competitive triathletes Connie McDonald and Pam Weekes to create an energy-dense cookie for endurance training, Levain's tiny subterranean bakery on W 74th Street became a worldwide culinary sensation. Their golden, crusty exterior gives way to an ultra-molten, cake-like dough interior.",
    mustTry: ["Chocolate Chip Walnut Cookie", "Dark Chocolate Peanut Butter Chip", "Two Chip Chocolate Chip", "Sour Cream Coffee Cake"],
    proTip: "One cookie is dense enough to share between two people. Grab a hot coffee, walk two blocks east into Central Park's Strawberry Fields, and enjoy it on a bench.",
    tags: ["Bakery", "Dessert", "Cookies", "Central Park Adjacent"]
  },
  {
    id: "peter-luger-steak-house",
    name: "Peter Luger Steak House",
    category: "eat",
    subCategory: "Historic Dry-Aged Porterhouse",
    borough: "Brooklyn",
    neighborhood: "Williamsburg",
    address: "178 Broadway, Brooklyn, NY 11211",
    subway: "J, M, Z to Marcy Ave",
    price: "$$$$",
    rating: 4.6,
    reviewsCount: "18,000+",
    image: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Serving USDA Prime dry-aged porterhouse steaks in Brooklyn since 1887.",
    fullDesc: "Since 1887 under the shadow of the Williamsburg Bridge, Peter Luger is the patriarch of the American steakhouse. Meat is hand-selected at wholesale markets and dry-aged on site in controlled humidity rooms, then broiled in high-temperature ovens and served sizzling in melted clarified butter on tilted platters.",
    mustTry: ["Steak for Two (or Three or Four) USDA Prime Porterhouse", "Extra Thick Cut Sizzling Bacon", "Luger's Special German Fried Potatoes", "Luger's Own Sauce with Tomatoes & Onions"],
    proTip: "Debit cards, cash, or the exclusive 'Peter Luger Card' only—no standard credit cards accepted! Book weeks in advance for weekend dinners.",
    tags: ["Steakhouse", "Historic", "Brooklyn", "Carnivore"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Peter_Luger_Steak_House"
  },
  {
    id: "golden-mall-flushing",
    name: "New World Mall & Flushing Chinatown",
    category: "eat",
    subCategory: "Authentic Pan-Asian Food Court",
    borough: "Queens",
    neighborhood: "Flushing",
    address: "136-20 Roosevelt Ave, Flushing, NY 11354",
    subway: "7 train to Flushing-Main St (last stop)",
    price: "$",
    rating: 4.8,
    reviewsCount: "11,000+",
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The largest, most energetic Chinatown in NYC with underground stalls serving regional specialties.",
    fullDesc: "Flushing's Chinatown is vastly larger and more culinary-diverse than Manhattan's. The basement food court of New World Mall hosts dozens of independent stalls preparing Xi'an hand-pulled cumin lamb noodles, Taiwanese beef noodle soup, Sichuan dry hot pots, and Uyghur lamb skewers.",
    mustTry: ["Xi'an Hand-Ripped 'Biang Biang' Noodles", "Xiao Long Bao (Soup Dumplings)", "Sichuan Spicy Hot Pot", "Fresh Taiwanese Boba Tea"],
    proTip: "Ride the 7 train to its final stop. Walk down into the basement level of New World Mall with cash or mobile pay, sample small dishes from 3 different stalls, and explore Roosevelt Ave.",
    tags: ["Queens", "Asian Cuisine", "Flushing", "Budget Friendly", "Spicy"]
  },

  // ==========================================
  // BEST PLACES TO VISIT & SIGHTS
  // ==========================================
  {
    id: "central-park",
    name: "Central Park",
    category: "visit",
    subCategory: "Urban Oasis & Landscape Masterpiece",
    borough: "Manhattan",
    neighborhood: "Uptown Manhattan (59th to 110th St)",
    address: "Central Park, New York, NY",
    subway: "A, B, C, D, 1 to 59th St-Columbus Circle or N, R, W to 5th Ave-59th St",
    price: "Free",
    rating: 4.9,
    reviewsCount: "250,000+",
    image: "https://images.unsplash.com/photo-1576402187878-974f70c890a5?auto=format&fit=crop&w=800&q=80",
    shortDesc: "843 acres of sculpted landscapes, lakes, bridges, and woodlands in the center of Manhattan.",
    fullDesc: "Designed by visionary landscape architects Frederick Law Olmsted and Calvert Vaux and opened in 1858, Central Park is an 843-acre masterpiece of civil engineering. Despite appearing entirely natural, virtually every hill, tree, pond, and stone outcrop was meticulously sculpted by human hands.",
    mustTry: ["Bethesda Terrace & Angel of the Waters Fountain", "Bow Bridge (most photographed cast-iron bridge)", "The Ramble (wild woodlands)", "Sheep Meadow skyline view", "Strawberry Fields (John Lennon memorial)"],
    proTip: "Rent a Citi Bike to loop the main outer drives, but explore the interior walkways and Ramble on foot—bicycles are prohibited on pedestrian paths. Don't miss the remote north woods near the Harlem Meer for quiet solitude.",
    tags: ["Iconic", "Nature", "Photography", "Free", "Architecture"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Central_Park"
  },
  {
    id: "the-met-museum",
    name: "The Metropolitan Museum of Art (The Met)",
    category: "visit",
    subCategory: "World-Class Museum",
    borough: "Manhattan",
    neighborhood: "Upper East Side / Museum Mile",
    address: "1000 5th Ave, New York, NY 10028",
    subway: "4, 5, 6 to 86th St",
    price: "$$$",
    rating: 4.9,
    reviewsCount: "110,000+",
    image: "https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Over 5,000 years of global human artistic genius spanning two million square feet.",
    fullDesc: "The largest art museum in the Americas and one of the most visited in the world, The Met holds over two million works spanning classical antiquity, ancient Egypt, European master paintings, American wing period rooms, Islamic art, and armor collections.",
    mustTry: ["The Temple of Dendur (authentic Egyptian sandstone temple set in a glass atrium)", "European Masters (Vermeer, Rembrandt, Van Gogh's 'Self-Portrait with Straw Hat')", "The American Wing Courtyard", "Cantor Rooftop Garden (panoramic skyline & park views)"],
    proTip: "NY, NJ, and CT residents enjoy 'Pay-What-You-Wish' admission at the ticket counters with valid ID. In spring and summer, head straight to the 5th floor elevator to access the Cantor Rooftop for drinks overlooking the Central Park canopy.",
    tags: ["Museum", "Art", "Culture", "Historic", "Rainy Day"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Metropolitan_Museum_of_Art"
  },
  {
    id: "brooklyn-bridge-and-dumbo",
    name: "Brooklyn Bridge & DUMBO Waterfront",
    category: "visit",
    subCategory: "Engineering Icon & Skyline",
    borough: "Brooklyn",
    neighborhood: "DUMBO / Brooklyn Heights",
    address: "Brooklyn Bridge Promenade, New York, NY 10038",
    subway: "A, C to High St or 4, 5, 6 to Brooklyn Bridge-City Hall",
    price: "Free",
    rating: 4.9,
    reviewsCount: "140,000+",
    image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Walk the 1.1-mile Gothic stone suspension bridge completed in 1883, into DUMBO's cobblestones.",
    fullDesc: "One of the greatest engineering feats of the 19th century, designed by John Augustus Roebling and completed under the supervision of his daughter-in-law Emily Warren Roebling. The elevated pedestrian promenade offers unparalleled views of Lower Manhattan, the East River, and Governors Island.",
    mustTry: ["Walk from Brooklyn towards Manhattan for the best skyline angles", "Washington Street in DUMBO (famous photo framing Manhattan Bridge and Empire State Building)", "Jane's Carousel in Brooklyn Bridge Park", "Time Out Market Rooftop"],
    proTip: "Walk at sunrise or after 9:30 PM to avoid heavy crowds. Starting on the Brooklyn side walking into Manhattan gives you the skyline growing in front of you the entire way.",
    tags: ["Landmark", "Free", "Scenic Views", "Architecture", "Sunset"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Brooklyn_Bridge"
  },
  {
    id: "high-line-and-little-island",
    name: "The High Line & Little Island",
    category: "visit",
    subCategory: "Elevated Park & Hudson Waterfront",
    borough: "Manhattan",
    neighborhood: "Chelsea / Meatpacking District",
    address: "Gansevoort St to W 34th St, New York, NY 10014",
    subway: "A, C, E, L to 14th St-8th Ave or 7 to 34th St-Hudson Yards",
    price: "Free",
    rating: 4.8,
    reviewsCount: "85,000+",
    image: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80",
    shortDesc: "A 1.45-mile elevated public park built on a historic freight rail line above Manhattan's West Side.",
    fullDesc: "Spanning from the Meatpacking District to Hudson Yards, the High Line rescued an abandoned 1930s viaduct from demolition, transforming it into an internationally lauded linear garden featuring native wildflowers, contemporary outdoor art installations, and sunken Hudson River overlooks. Just steps off Pier 55 sits Little Island, an undulating futuristic floating park on 132 tulip-shaped concrete pilings.",
    mustTry: ["10th Avenue Square viewing amphitheater", "Chelsea Market passage", "Strolling Little Island's amphitheater over the Hudson water", "Sunset over New Jersey across the Hudson"],
    proTip: "Enter at Gansevoort Street in Meatpacking, stroll north along the High Line, and exit at 34th Street into the dramatic Vessel and Hudson Yards development.",
    tags: ["Park", "Modern Architecture", "Outdoor", "Free", "Art"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/High_Line"
  },
  {
    id: "summit-one-vanderbilt",
    name: "Summit One Vanderbilt",
    category: "visit",
    subCategory: "Immersive Sky Deck",
    borough: "Manhattan",
    neighborhood: "Midtown East",
    address: "45 E 42nd St, New York, NY 10017",
    subway: "4, 5, 6, 7, S to Grand Central-42nd St",
    price: "$$$",
    rating: 4.8,
    reviewsCount: "35,000+",
    image: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80",
    shortDesc: "An immersive multi-sensory mirrored observatory 1,200 feet above Grand Central Terminal.",
    fullDesc: "Unlike traditional observation decks, Summit One Vanderbilt combines multi-room mirrored art installations (designed by Kenzo Digital), infinity-room illusion spaces ('Air'), reflective silver helium orbs ('Affinity'), and glass sky-boxes cantilevered 1,063 feet directly over Madison Avenue with jaw-dropping views of the Chrysler Building and Empire State.",
    mustTry: ["Kenzo Digital's 'Air' mirrored infinity room", "'Affinity' room filled with floating silver spheres", "'Levitation' glass ledge boxes", "Après terrace for cocktails overlooking the skyline"],
    proTip: "Because the floors and ceilings are mirrors, wear pants or shorts (avoid dresses/skirts), and bring sunglasses as daytime sun bounces intensely. Free shoe covers are provided at check-in.",
    tags: ["Skyscraper", "Observation Deck", "Modern", "Photography"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/One_Vanderbilt"
  },
  {
    id: "grand-central-terminal",
    name: "Grand Central Terminal",
    category: "visit",
    subCategory: "Beaux-Arts Cathedral of Transit",
    borough: "Manhattan",
    neighborhood: "Midtown East",
    address: "89 E 42nd St, New York, NY 10017",
    subway: "4, 5, 6, 7, S directly underneath",
    price: "Free",
    rating: 4.8,
    reviewsCount: "95,000+",
    image: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The 1913 Beaux-Arts masterpiece with its celestial ceiling, four-faced brass clock, and acoustic secrets.",
    fullDesc: "Grand Central is the world's largest train station by number of platforms (44 platforms on two subterranean levels). Saved from demolition in the 1970s by Jacqueline Kennedy Onassis, it features a towering Main Concourse with a turquoise astronomical ceiling depicting 2,500 stars (famously painted backwards from God's celestial view).",
    mustTry: ["The Whispering Gallery outside the Oyster Bar (whisper into diagonally opposite ceramic arches)", "Four-Faced Brass Opal Clock worth over $10 million", "Grand Central Oyster Bar (shucking oysters since 1913)"],
    proTip: "Find the tiny black brick smudge on the northwest corner of the celestial ceiling—restorers purposely left one patch uncleaned during the 1998 restoration to demonstrate the layers of 20th-century cigarette smoke and coal soot that once blackened the hall.",
    tags: ["Historic", "Architecture", "Free", "Subway Lore"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Grand_Central_Terminal"
  },
  {
    id: "tenement-museum",
    name: "The Tenement Museum",
    category: "visit",
    subCategory: "Living Immigration History",
    borough: "Manhattan",
    neighborhood: "Lower East Side",
    address: "97 & 103 Orchard St, New York, NY 10002",
    subway: "F, M, J, Z to Delancey St-Essex St",
    price: "$$",
    rating: 4.9,
    reviewsCount: "11,000+",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Step inside preserved 19th and 20th-century immigrant tenement apartments to experience real stories.",
    fullDesc: "Housed in two actual Lower East Side tenement buildings where over 15,000 working-class immigrants from more than 20 nations lived between 1863 and 2011. Guided tours take visitors through painstakingly restored apartments that recreate the authentic lives of Irish, Jewish, Italian, and German families who forged New York's cultural fabric.",
    mustTry: ["Hard Times: 1880s / 1930s Apartment Tour", "Irish Outsiders Tour", "Under One Roof: Post-WWII garment workers tour", "Walking tour of historic Lower East Side streets"],
    proTip: "You must book guided tour tickets online in advance; there is no unguided walk-through access. Tours are intimate (max 15 people) and give you an emotional, ground-level understanding of what building NYC really meant.",
    tags: ["History", "Immigration", "Lower East Side", "Museum"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Tenement_Museum"
  },
  {
    id: "statue-of-liberty-ellis-island",
    name: "Statue of Liberty & Ellis Island",
    category: "visit",
    subCategory: "Beacon of Freedom",
    borough: "Manhattan",
    neighborhood: "New York Harbor",
    address: "Battery Park Ferry Departure, New York, NY 10004",
    subway: "1 to South Ferry or 4, 5 to Bowling Green",
    price: "$$",
    rating: 4.8,
    reviewsCount: "135,000+",
    image: "https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&w=800&q=80",
    shortDesc: "France's gift of freedom dedicated in 1886 and the historic gateway through which 12 million Americans entered.",
    fullDesc: "Designed by French sculptor Frédéric-Auguste Bartholdi with internal iron framework engineered by Gustave Eiffel, 'Liberty Enlightening the World' stands 305 feet tall. Ellis Island's Great Hall served as the federal immigration station from 1892 to 1954; an estimated 40% of all current US citizens can trace at least one ancestor through this island.",
    mustTry: ["Ellis Island National Museum of Immigration Great Hall & passenger manifest search", "Pedestal / Crown Walk", "Views of the harbor from the ferry deck"],
    proTip: "Budget Tip: If you just want majestic views of Lady Liberty without paying for the official ferry tour, hop on the 100% free Staten Island Ferry from Whitehall Terminal—it sails directly past the statue with brilliant skyline views, 24/7!",
    tags: ["Landmark", "History", "National Monument", "Ferry"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Statue_of_Liberty"
  },
  {
    id: "911-memorial-and-museum",
    name: "9/11 Memorial & Museum & Oculus",
    category: "visit",
    subCategory: "Memorial & Contemporary Architecture",
    borough: "Manhattan",
    neighborhood: "Financial District / World Trade Center",
    address: "180 Greenwich St, New York, NY 10007",
    subway: "E to World Trade Center, 1 to WTC Cortlandt, or R, W to Cortlandt St",
    price: "$$",
    rating: 4.9,
    reviewsCount: "115,000+",
    image: "https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The somber reflecting twin pools set within original Twin Towers footprints and Calatrava's winged Oculus.",
    fullDesc: "Honoring the 2,977 victims of the September 11, 2001 attacks, architect Michael Arad's 'Reflecting Absence' features two monumental recessed cascading water pools within the exact footprints of the Twin Towers, surrounded by swamp white oak trees. Adjacent sits Santiago Calatrava's \$4 billion white ribbed 'Oculus' transportation hub, symbolizing a dove released from a child's hands.",
    mustTry: ["Twin Reflecting Pools engraved with victims' names", "Historical exhibition inside the subterranean Museum", "The Survivor Tree", "Oculus skylight (aligned with the sun on Sept 11 at 10:28 AM)"],
    proTip: "Visiting the outdoor plaza and twin pools is completely free and open to the public daily until midnight. To enter the underground museum, book a timed entry ticket well ahead.",
    tags: ["Memorial", "History", "Architecture", "Must Visit"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/National_September_11_Memorial_%26_Museum"
  },
  {
    id: "snug-harbor-staten-island",
    name: "Snug Harbor Cultural Center & Chinese Scholar's Garden",
    category: "visit",
    subCategory: "Botanical Oasis & Heritage",
    borough: "Staten Island",
    neighborhood: "Livingston / Randall Manor",
    address: "1000 Richmond Terrace, Staten Island, NY 10301",
    subway: "Staten Island Ferry from Manhattan + S40 Bus",
    price: "$",
    rating: 4.7,
    reviewsCount: "3,200+",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    shortDesc: "An 83-acre hidden cultural jewel featuring Greek Revival temples and an authentic Ming Dynasty scholar's garden.",
    fullDesc: "Founded in 1801 as a retirement home for aged maritime sailors ('Sailors' Snug Harbor'), this sprawling cultural center contains 28 historic Greek Revival and Beaux-Arts buildings, the Staten Island Botanical Garden, and the New York Chinese Scholar's Garden—one of only two authentic outdoor Chinese scholar's gardens in the US, built with precision joinery without nails by craftsmen from Suzhou, China.",
    mustTry: ["New York Chinese Scholar's Garden pavilions and koi ponds", "Greek Revival Temple buildings along the North Shore", "Tuscan Garden inspired by Villa Gamberaia"],
    proTip: "Combine this with the free Staten Island Ferry ride! Once at St. George Terminal, hop on the S40 bus for a 10-minute ride to Snug Harbor's gates.",
    tags: ["Staten Island", "Garden", "Hidden Gem", "Historic", "Peaceful"]
  },

  // ==========================================
  // NIGHTLIFE & ENTERTAINMENT
  // ==========================================
  {
    id: "comedy-cellar",
    name: "The Comedy Cellar",
    category: "nightlife",
    subCategory: "Legendary Stand-Up Comedy",
    borough: "Manhattan",
    neighborhood: "Greenwich Village",
    address: "117 MacDougal St, New York, NY 10012",
    subway: "A, C, E, B, D, F, M to W 4th St-Wash Sq",
    price: "$$",
    rating: 4.9,
    reviewsCount: "14,000+",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The world's most famous comedy club where superstars regularly drop in unannounced.",
    fullDesc: "Founded in 1982 by stand-up comedian Bill Grundfest, this low-ceilinged basement club on MacDougal Street with its iconic stained-glass logo and brick wall is the Holy Grail of stand-up comedy. Jerry Seinfeld, Chris Rock, Dave Chappelle, Jon Stewart, and Ali Wong are known to drop in unannounced to test new material.",
    mustTry: ["7-comedian showcase lineup", "Classic Village cocktail and hummus platter", "Late-night Friday/Saturday showcase"],
    proTip: "Reservations open online exactly one week in advance and vanish in minutes. There is a strict two-item food/drink minimum per person inside. Phones are placed into locked pouches upon entering—strictly zero texting or recording.",
    tags: ["Comedy", "Greenwich Village", "Celebrity Drops", "Late Night"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Comedy_Cellar"
  },
  {
    id: "village-vanguard",
    name: "Village Vanguard",
    category: "nightlife",
    subCategory: "Historic Jazz Shrine",
    borough: "Manhattan",
    neighborhood: "West Village",
    address: "178 7th Ave S, New York, NY 10014",
    subway: "1, 2, 3 to 14th St or 1 to Christopher St-Sheridan Sq",
    price: "$$$",
    rating: 4.8,
    reviewsCount: "5,800+",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80",
    shortDesc: "The most sacred basement in jazz history, operating since 1935 with peerless natural acoustics.",
    fullDesc: "Descending the steep steps beneath the iconic red-and-white awning on Seventh Avenue South brings you into jazz ground zero. Since Max Gordon opened it in 1935, John Coltrane, Miles Davis, Bill Evans, Thelonious Monk, and Sonny Rollins have recorded legendary live albums inside this wedge-shaped cellar.",
    mustTry: ["Vanguard Jazz Orchestra (every Monday night since 1966)", "Old Fashioned or Manhattan cocktail", "Listening in total reverence with zero whispering permitted during sets"],
    proTip: "Seating is first-come, first-served when doors open 30 minutes prior to set times (usually 8:00 PM and 10:00 PM). Line up 45 minutes early on Seventh Avenue to grab a table right in front of the piano.",
    tags: ["Jazz", "Historic", "West Village", "Acoustics"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Village_Vanguard"
  },
  {
    id: "pdt-please-dont-tell",
    name: "PDT (Please Don't Tell)",
    category: "nightlife",
    subCategory: "Secret Speakeasy",
    borough: "Manhattan",
    neighborhood: "East Village",
    address: "113 St Marks Pl, New York, NY 10009",
    subway: "6 to Astor Place or L to 1st Ave",
    price: "$$$",
    rating: 4.7,
    reviewsCount: "4,600+",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Enter through a vintage wooden phone booth inside a hot dog shop into an intimate cocktail den.",
    fullDesc: "PDT ignited the 21st-century craft cocktail speakeasy movement. To enter, you walk into 'Crif Dogs' hot dog joint, step into a vintage 1940s phone booth on the wall, pick up the rotary receiver, and dial '1'. The faux back wall swings open to reveal a low-lit, taxidermy-adorned cocktail bar spearheaded by legendary mixologist Jim Meehan.",
    mustTry: ["Benton's Old Fashioned (infused with bacon-fat bourbon and maple syrup)", "Paddington (rum, marmalade, absinthe)", "Bacon-wrapped deep-fried hot dogs from Crif Dogs"],
    proTip: "Reservations open same-day at 3:00 PM via Resy. If you don't get one, walk into Crif Dogs at 5:00 PM right when they open and ask the hostess for bar seats or walk-in waitlist.",
    tags: ["Speakeasy", "Cocktails", "East Village", "Hidden Gem"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/PDT_(bar)"
  },
  {
    id: "the-dead-rabbit",
    name: "The Dead Rabbit",
    category: "nightlife",
    subCategory: "Award-Winning Irish Cocktail Taproom",
    borough: "Manhattan",
    neighborhood: "Financial District",
    address: "30 Water St, New York, NY 10004",
    subway: "1 to South Ferry or R, W to Whitehall St",
    price: "$$$",
    rating: 4.8,
    reviewsCount: "8,300+",
    image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Voted World's Best Bar, blending 19th-century Irish-American history with precision craft cocktails.",
    fullDesc: "Named after the notorious 1850s Bowery gang led by John Morrissey, The Dead Rabbit spans three floors in an 1828 red-brick building. Downstairs is a sawdust-strewn traditional Irish pub with draft Guinness and live trad sessions; upstairs is The Parlor, serving world-class cocktails with a graphic-novel menu.",
    mustTry: ["The Dead Rabbit Irish Coffee (fresh nutmeg, rich cream float)", "Psycho Killer cocktail", "Scotch Egg and Fish & Chips"],
    proTip: "The ground-floor Taproom is walk-in only and has a boisterous, friendly vibe with world-class Guinness pours. Head upstairs to The Parlor for the cocktail tasting experience.",
    tags: ["Irish Pub", "Cocktails", "Historic", "World's Best Bar"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/The_Dead_Rabbit"
  },
  {
    id: "westlight-brooklyn",
    name: "Westlight at The William Vale",
    category: "nightlife",
    subCategory: "Skyline Rooftop Bar",
    borough: "Brooklyn",
    neighborhood: "Williamsburg",
    address: "111 N 12th St 22nd Floor, Brooklyn, NY 11249",
    subway: "L to Bedford Ave or G to Nassau Ave",
    price: "$$$",
    rating: 4.7,
    reviewsCount: "6,900+",
    image: "https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80",
    shortDesc: "22nd-floor panoramic glass terrace offering the most breathtaking full skyline view of Manhattan.",
    fullDesc: "Perched atop Williamsburg's modern William Vale hotel, Westlight offers a 360-degree sweep of Manhattan, Queens, Brooklyn, and the East River. Chef Andrew Carmellini's team pairs creative cocktails with globally inspired small bites like charred edamame and duck carnitas tacos.",
    mustTry: ["The Sling Shot cocktail", "Charred Edamame with spicy togarashi", "Spiced Chicken Empanadas"],
    proTip: "Book an outdoor terrace table 45 minutes before sunset. Watching the golden hour light reflect across the glass towers of Manhattan, followed by the skyline lighting up like diamonds, is an unforgettable NYC spectacle.",
    tags: ["Rooftop", "Skyline Views", "Williamsburg", "Cocktails", "Sunset"]
  },
  {
    id: "house-of-yes",
    name: "House of Yes",
    category: "nightlife",
    subCategory: "Immersive Dance & Circus Club",
    borough: "Brooklyn",
    neighborhood: "Bushwick",
    address: "2 Wyckoff Ave, Brooklyn, NY 11237",
    subway: "L to Jefferson St",
    price: "$$",
    rating: 4.7,
    reviewsCount: "5,100+",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    shortDesc: "A wild, celebratory, artist-founded wonderland of aerial acrobats, theatrical performers, and house beats.",
    fullDesc: "In the heart of creative Bushwick, House of Yes is world-renowned for its radical inclusivity, avant-garde costume themes, aerialists dangling from the rafters, and immersive dance floors. It rejects standard club pretension in favor of pure self-expression and joyous community.",
    mustTry: ["Themed costume nights", "Aerial circus cabaret shows", "Outdoor courtyard vibes"],
    proTip: "Express your creativity with your outfit! Most parties have specific creative dress codes (glitter, disco, neon, leather, mythical beasts); attendees who make an effort in costume are celebrated and often skip general entry lines.",
    tags: ["Dance Club", "Circus", "Bushwick", "LGBTQ+ Friendly", "Music"]
  },
  {
    id: "broadway-theatre-district",
    name: "Broadway & The Theater District",
    category: "nightlife",
    subCategory: "World Capital of Theater",
    borough: "Manhattan",
    neighborhood: "Theater District / Midtown West",
    address: "Broadway & 42nd to 54th St, New York, NY 10036",
    subway: "N, Q, R, W, 1, 2, 3, 7 to Times Sq-42nd St",
    price: "$$$$",
    rating: 4.9,
    reviewsCount: "80,000+",
    image: "https://images.unsplash.com/photo-1508050919630-b135583b29ab?auto=format&fit=crop&w=800&q=80",
    shortDesc: "41 historic professional theaters presenting the highest echelon of live dramatic art in the English-speaking world.",
    fullDesc: "Attracting over 13 million theatergoers annually, Broadway represents the pinnacle of commercial live entertainment. From historic gilded playhouses like the Lyceum (built 1903) and Majestic to long-running blockbusters like Hamilton, The Lion King, and Wicked, the electric buzz of theater curtains rising at 8:00 PM is unmatched.",
    mustTry: ["Seeing a Tony-Award winning musical or drama", "Grabbing a pre-show martini at Joe Allen on Restaurant Row", "Meeting the cast at the stage door post-curtain call"],
    proTip: "Visit the red glass TKTS booth under the stairs at Duffy Square (Father Duffy Square / 47th St) on the day of the show for 20% to 50% discount tickets, or enter online digital ticket lotteries (Broadway Direct, Lucky Seat, TodayTix) for $30–$49 rush seats.",
    tags: ["Broadway", "Theater", "Musical", "Culture", "Bucket List"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Broadway_theatre"
  },
  {
    id: "flushing-meadows-corona-park",
    name: "Flushing Meadows Corona Park & The Unisphere",
    category: "visit",
    subCategory: "Historic World's Fair Grounds",
    borough: "Queens",
    neighborhood: "Flushing / Corona",
    address: "Flushing Meadows Corona Park, Queens, NY",
    subway: "7 train to Mets-Willets Point",
    price: "Free",
    rating: 4.8,
    reviewsCount: "32,000+",
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Site of two World's Fairs (1939 & 1964), featuring the monumental 12-story steel Unisphere globe.",
    fullDesc: "Spanning 897 acres (larger than Central Park), Flushing Meadows hosted the 1939 and 1964 New York World's Fairs. The iconic stainless steel Unisphere—commissioned for the 1964 Fair to celebrate the dawn of the Space Age—soars 140 feet high. The park also houses the Queens Museum with its breathtaking, room-sized 'Panorama of the City of New York' (an exact scale miniature model of all five boroughs containing 895,000 individual buildings).",
    mustTry: ["Standing under the giant Unisphere fountains", "Viewing the NYC 3D scale Panorama at the Queens Museum", "Visiting the iconic New York State Pavilion observation towers", "USTA Billie Jean King National Tennis Center (home of the US Open)"],
    proTip: "Combine your visit with food in nearby Corona: walk 10 minutes to the Lemon Ice King of Corona on 108th St for authentic Italian water ice in over 30 flavors.",
    tags: ["Queens", "World Fair", "Free", "Architecture", "Museum"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Flushing_Meadows%E2%80%93Corona_Park"
  },
  {
    id: "yankee-stadium-bronx",
    name: "Yankee Stadium",
    category: "visit",
    subCategory: "Cathedral of Baseball",
    borough: "The Bronx",
    neighborhood: "Concourse",
    address: "1 E 161st St, Bronx, NY 10451",
    subway: "4, B, D to 161st St-Yankee Stadium",
    price: "$$$",
    rating: 4.8,
    reviewsCount: "42,000+",
    image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Home of the 27-time World Series Champions, featuring Monument Park and legendary baseball lore.",
    fullDesc: "Successor to 'The House That Ruth Built', the current Yankee Stadium opened in 2009, meticulously incorporating the classic 1923 exterior limestone facade and signature copper frieze. Behind the centerfield wall lies Monument Park, an open-air museum honoring baseball titans like Babe Ruth, Lou Gehrig, Joe DiMaggio, Mickey Mantle, and Derek Jeter.",
    mustTry: ["Monument Park before the game starts", "New York Yankees Museum inside the Great Hall", "Garlic Fries and 99 Burger", "Singing along to Frank Sinatra's 'Theme from New York, New York' at the end of every game"],
    proTip: "Take the 4 or D train directly to 161st St. Gates open 90 minutes prior to first pitch, giving you plenty of time to explore Monument Park, which closes 45 minutes before game time.",
    tags: ["Sports", "Bronx", "Baseball", "Historic"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Yankee_Stadium"
  },
  {
    id: "blue-note-jazz-club",
    name: "Blue Note Jazz Club",
    category: "nightlife",
    subCategory: "Intimate World Jazz Mecca",
    borough: "Manhattan",
    neighborhood: "Greenwich Village",
    address: "131 W 3rd St, New York, NY 10012",
    subway: "A, C, E, B, D, F, M to W 4th St-Wash Sq",
    price: "$$$$",
    rating: 4.7,
    reviewsCount: "7,800+",
    image: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Greenwich Village cultural mecca hosting Grammy-winning jazz icons, fusion masters, and hip-hop improvisers.",
    fullDesc: "Established in 1981 by Danny Bensusan, the Blue Note is one of the premier jazz venues in the world. Legendary musicians such as Dizzy Gillespie, Sarah Vaughan, Ray Charles, and Chick Corea made it their home stage. Today, it showcases legends alongside genre-bending modern artists like Robert Glasper, Kamasi Washington, and Norah Jones.",
    mustTry: ["Late-night sets (10:30 PM / 12:30 AM)", "Signature Manhattan or Blue Note Martini", "Weekend Jazz Brunch with live music"],
    proTip: "Bar seating is significantly cheaper than table reservations and provides an intimate, elevated line-of-sight directly into the musicians' hands. Reserve weeks in advance for Robert Glasper's annual fall residency.",
    tags: ["Jazz", "Greenwich Village", "Live Music", "Legendary"],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Blue_Note_Jazz_Club"
  },
  {
    id: "lees-tavern-staten-island",
    name: "Lee's Tavern",
    category: "eat",
    subCategory: "Historic Thin-Crust Tavern Bar Pie",
    borough: "Staten Island",
    neighborhood: "Dongan Hills",
    address: "60 Hancock St, Staten Island, NY 10305",
    subway: "Staten Island Railway (SIR) to Dongan Hills",
    price: "$",
    rating: 4.8,
    reviewsCount: "2,400+",
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=800&q=80",
    shortDesc: "Unapologetic, neon-lit neighborhood tavern dishing out razor-thin, crispy bar pies since 1940.",
    fullDesc: "Opposite the Dongan Hills train station on Staten Island, Lee's Tavern has been pouring cold beer and baking crackly, paper-thin bar pizzas since 1940. With wood-paneled walls, a long wooden bar, and zero pretense, it embodies old-school New York neighborhood camaraderie.",
    mustTry: ["Clam Pie with fresh garlic and oregano", "Sausage & Hot Pepper Bar Pie", "Pitcher of draft beer"],
    proTip: "It's cash-only! Take the free Staten Island Ferry from Manhattan to St. George, hop on the Staten Island Railway (SIR) to Dongan Hills, and step right across the street into Lee's for one of the greatest bar pies in the state.",
    tags: ["Pizza", "Staten Island", "Historic", "Budget Friendly", "Cash Only"]
  }
];
